# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a249a6518533f2a62887bfd12e7ab6aa1c3cf6bc6f21534651b7128a6987ed54a60fbd0d716c70a3925a1f38821a57f6757dd6f94918f1d46ea9cf9c50cd5e7e

test:
  secret_key_base: 1211ba523f105385f0f39567d3d690736e79f0c6eb3ff8e7d93b01fc27a91bee6c031113dc35ad4404e632542a56eceed57adcf350a34c0c104cf011b5c002dc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
